version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.7.9
  build:
    commands:
      # aws s3 mb s3://sam-code-bucket-3

      #- sam package --template-file template.yaml --s3-bucket sam-code-artifacts-3 --output-template-file packaged.yaml
      - aws cloudformation package --s3-bucket sam-code-bucket-3 --template-file template.yaml --output-template-file template-generated.yaml --profile adminuser
      #- sam deploy --template-file packaged.yaml --stack-name iteration3-sam --capabilities CAPABILITY_IAM
      #- aws cloudformation deploy --guided --template-file template-generated.yaml --stack-name iteration3-sam --capabilities CAPABILITY_IAM
