version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      # aws s3 mb s3://sam-code-artifacts-3

      - sam package --template-file template.yaml --s3-bucket sam-code-artifacts-3 --output-template-file packaged.yaml

      - sam deploy --template-file packaged.yaml --stack-name iteration3-sam --capabilities CAPABILITY_IAM

#this is a 4th automatic test
