AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  A simple backend (read/write to DynamoDB) with a RESTful API endpoint using Amazon API Gateway.

Globals:
  #https://github.com/awslabs/serverless-application-model/blob/develop/docs/globals.rst
  Function:
    Runtime: python3.8
    MemorySize: 128
    Environment:
      Variables:
        TABLE_NAME: !Ref Table
        REGION_NAME: !Ref AWS::Region

Resources:
  httpendpoint3:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function3.lambda_handler
      CodeUri: src/
      Description: >-
        A simple backend (read/write to DynamoDB) with a RESTful API endpoint using Amazon API Gateway.
      Timeout: 3
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Table
      Events:
        Api3:
          Type: Api
          Properties:
            Path: /MyResource
            Method: GET

  Table:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: info
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
