AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  Iteration 3.X - Basic
Globals:
  #https://github.com/awslabs/serverless-application-model/blob/develop/docs/globals.rst
  Function:
    Runtime: python3.8
    MemorySize: 128
    Timeout: 3
    Environment:
      Variables:
        REGION_NAME: !Ref AWS::Region

Resources:
  httpendpoint3:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function3.lambda_handler
      CodeUri: .src/
      Description: A starter AWS Lambda function.
      Events:
          HelloWorldApi:
          Type: Api
          Properties:
            Path: /MyResource
            Method: GET
