AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  Iteration 3.1 - A simple backend (read/write to DynamoDB) with a RESTful API endpoint using Amazon API Gateway.

Globals:
  #https://github.com/awslabs/serverless-application-model/blob/develop/docs/globals.rst
  Function:
    Runtime: python3.8
    MemorySize: 128
    Environment:
      Variables:
        TABLE_NAME: !Ref Table
        REGION_NAME: !Ref AWS::Region

Resources:
  Api3:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

  httpendpoint3:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function3.lambda_handler
      CodeUri: src/

      Events:
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref Api3
            Path: /MyResource
            Method: GET
